'use client';
import { useState, useEffect, useCallback } from 'react';
import Link from 'next/link';
import { supabase } from '../lib/supabaseClient';
import { WAIVER_TYPES, WAIVER_TYPE_LABELS, WAIVER_STATUS } from '../lib/lienWaivers';

function fmtDate(v) {
  if (!v) return '—';
  return new Date(v.length === 10 ? v + 'T00:00:00' : v).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
}
function fmtMoney(v) {
  if (v === null || v === undefined || v === '') return '—';
  return '$' + Number(v).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

const today = () => new Date().toISOString().slice(0, 10);

// Financials → Lien Waivers. Request a waiver from a sub (or send one to the
// owner), and see who has signed. Wording is generated by the database and
// frozen at request time — see migration 134. To change a waiver, void it
// and request a new one.
export default function LienWaiversCard({ jobId, job, onChanged }) {
  const [waivers, setWaivers] = useState([]);
  const [workOrders, setWorkOrders] = useState([]);
  const [companies, setCompanies] = useState({});
  const [payApps, setPayApps] = useState([]);
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ direction: 'from_sub', work_order_id: '', company_id: '', waiver_type: 'conditional_progress', through_date: today(), payment_amount: '', pay_app_id: '' });
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [openId, setOpenId] = useState(null);
  const [enforcement, setEnforcement] = useState('warn');
  const [optional, setOptional] = useState(!!job?.lien_waivers_optional);

  const load = useCallback(async () => {
    const [w, wo, pa, s] = await Promise.all([
      supabase.from('lien_waivers').select('*').eq('job_id', jobId).order('created_at', { ascending: false }),
      supabase.from('work_orders').select('id, company_id, trade, description, amount, status').eq('job_id', jobId).order('created_at'),
      supabase.from('pay_applications').select('id, application_no, period_to, status').eq('job_id', jobId).neq('status', 'void').order('application_no'),
      supabase.from('app_settings').select('waiver_enforcement').eq('id', 1).maybeSingle(),
    ]);
    setWaivers(w.data || []);
    setWorkOrders(wo.data || []);
    setPayApps(pa.data || []);
    if (s.data?.waiver_enforcement) setEnforcement(s.data.waiver_enforcement);
    const ids = [...new Set((wo.data || []).map(x => x.company_id).filter(Boolean))];
    if (ids.length) {
      const { data: cs } = await supabase.from('companies').select('id, company_name').in('id', ids);
      setCompanies(Object.fromEntries((cs || []).map(c => [c.id, c.company_name])));
    }
  }, [jobId]);

  useEffect(() => {
    load();
    const channel = supabase.channel(`waivers-${jobId}`)
      .on('postgres_changes', { event: '*', schema: 'public', table: 'lien_waivers', filter: `job_id=eq.${jobId}` }, load)
      .subscribe();
    return () => supabase.removeChannel(channel);
  }, [jobId, load]);

  function set(field, value) {
    setForm(prev => {
      const next = { ...prev, [field]: value };
      if (field === 'work_order_id') {
        const wo = workOrders.find(x => x.id === value);
        if (wo) { next.company_id = wo.company_id; if (!prev.payment_amount) next.payment_amount = wo.amount ?? ''; }
      }
      if (field === 'pay_app_id' && value) {
        const pa = payApps.find(x => x.id === value);
        if (pa?.period_to) next.through_date = pa.period_to;
      }
      if (field === 'direction') { next.work_order_id = ''; next.company_id = ''; }
      return next;
    });
  }

  async function toggleOptional(v) {
    setOptional(v);
    const { error: err } = await supabase.from('jobs').update({ lien_waivers_optional: v }).eq('id', jobId);
    if (err) { setOptional(!v); setError(err.message); }
  }

  const subOptions = [...new Set(workOrders.map(w => w.company_id).filter(Boolean))];

  async function submit(e) {
    e.preventDefault();
    setError('');
    if (form.direction === 'from_sub' && !form.company_id) { setError('Choose the subcontractor.'); return; }
    const amount = Number(String(form.payment_amount).replace(/[^0-9.]/g, ''));
    if (!Number.isFinite(amount) || amount < 0 || form.payment_amount === '') { setError('Enter the payment amount this waiver covers.'); return; }
    setSaving(true);
    const { error: err } = await supabase.from('lien_waivers').insert({
      job_id: jobId,
      direction: form.direction,
      company_id: form.direction === 'from_sub' ? form.company_id : null,
      work_order_id: form.direction === 'from_sub' && form.work_order_id ? form.work_order_id : null,
      pay_app_id: form.pay_app_id || null,
      waiver_type: form.waiver_type,
      through_date: form.through_date,
      payment_amount: amount,
    });
    setSaving(false);
    if (err) { setError(err.message); return; }
    setShowForm(false);
    setForm(f => ({ ...f, payment_amount: '', work_order_id: '' }));
    await load();
    if (onChanged) onChanged();
  }

  async function voidWaiver(w) {
    if (!confirm('Void this waiver? A signed waiver that is voided no longer counts as being on file. Its wording cannot be edited — request a new one if the terms were wrong.')) return;
    const { error: err } = await supabase.from('lien_waivers').update({ status: 'void' }).eq('id', w.id);
    if (err) { setError(err.message); return; }
    load();
  }

  async function markReceivedOnPaper(w) {
    const note = prompt('Note where the paper waiver is filed (e.g. "scanned into Documents"):');
    if (note === null) return;
    const { error: err } = await supabase.from('lien_waivers').update({ status: 'waived', notes: note.trim() || 'Received on paper' }).eq('id', w.id);
    if (err) { setError(err.message); return; }
    load();
  }

  async function remind(w) {
    const { error: err } = await supabase.from('portal_notifications').insert({
      recipient_kind: 'subcontractor', company_id: w.company_id, job_id: w.job_id, category: 'lien_waiver_requested',
      message: `Reminder: please sign the ${w.waiver_type.replace('_', ' ')} lien waiver for ${fmtMoney(w.payment_amount)} (through ${fmtDate(w.through_date)}).`,
      link_path: '/sub-portal/waivers', source_id: w.id,
    });
    if (err) { setError(err.message); return; }
    alert('Reminder sent.');
  }

  const subWaivers = waivers.filter(w => w.direction === 'from_sub');
  const ownerWaivers = waivers.filter(w => w.direction === 'to_owner');
  const outstanding = subWaivers.filter(w => w.status === 'requested' || w.status === 'rejected').length;

  function Row({ w }) {
    const st = WAIVER_STATUS[w.status] || WAIVER_STATUS.requested;
    const isOpen = openId === w.id;
    const overdue = w.status === 'requested' && w.due_date && w.due_date < today();
    return (
      <div style={{ borderBottom: '1px solid var(--line)', padding: '10px 0', fontSize: 13 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', gap: 10, alignItems: 'center' }}>
          <div style={{ cursor: 'pointer' }} onClick={() => setOpenId(isOpen ? null : w.id)}>
            <b>{w.direction === 'from_sub' ? (w.claimant_name || 'Subcontractor') : 'McLoud → Owner'}</b> — {fmtMoney(w.payment_amount)}
            <div style={{ fontSize: 11.5, color: 'var(--ink-soft)' }}>
              {WAIVER_TYPE_LABELS[w.waiver_type]} · through {fmtDate(w.through_date)}
              {w.signed_at ? ` · signed ${fmtDate(w.signed_at)}` : ''}
              {overdue ? ' · overdue' : ''}
            </div>
          </div>
          <span style={{ fontSize: 10.5, fontWeight: 700, padding: '2px 8px', borderRadius: 10, color: overdue ? '#a13f3f' : st.color, background: overdue ? '#fbeae7' : st.bg, whiteSpace: 'nowrap' }}>{overdue ? 'Overdue' : st.label}</span>
        </div>
        {isOpen && (
          <div style={{ marginTop: 10 }}>
            {w.status === 'rejected' && w.reject_reason && <div style={{ fontSize: 12, color: '#a13f3f', marginBottom: 6 }}>Sub says: {w.reject_reason}</div>}
            {w.notes && <div style={{ fontSize: 12, color: 'var(--ink-soft)', marginBottom: 6 }}>{w.notes}</div>}
            <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
              <Link className="btn btn-sm" href={`/jobs/${jobId}/waivers/${w.id}`}>{w.direction === 'to_owner' && w.status === 'requested' ? 'Open & sign' : 'View / print'}</Link>
              {w.direction === 'from_sub' && w.status === 'requested' && <button type="button" className="btn btn-sm" onClick={() => remind(w)}>Send reminder</button>}
              {w.direction === 'from_sub' && (w.status === 'requested' || w.status === 'rejected') && <button type="button" className="btn btn-sm" onClick={() => markReceivedOnPaper(w)}>Received on paper</button>}
              {w.status !== 'void' && w.status !== 'waived' && <button type="button" className="btn btn-sm btn-danger" onClick={() => voidWaiver(w)}>Void</button>}
            </div>
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="card">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 10, flexWrap: 'wrap' }}>
        <div>
          <h3 style={{ marginBottom: 2 }}>Lien Waivers</h3>
          <div style={{ fontSize: 12, color: 'var(--ink-soft)' }}>
            {outstanding > 0 ? `${outstanding} subcontractor waiver${outstanding === 1 ? '' : 's'} outstanding` : 'No subcontractor waivers outstanding'}
            {' · '}Enforcement: {enforcement}
            {optional ? ' · waivers optional on this job' : ''}
          </div>
          <label style={{ display: 'flex', gap: 6, alignItems: 'center', fontSize: 12, marginTop: 6, cursor: 'pointer' }}>
            <input type="checkbox" checked={optional} onChange={e => toggleOptional(e.target.checked)} style={{ width: 'auto' }} />
            Waivers not required on this job (skips the payment check and auto-requests)
          </label>
        </div>
        <button className="btn btn-sm" onClick={() => setShowForm(s => !s)}>{showForm ? 'Cancel' : '+ Request a waiver'}</button>
      </div>
      {error && <div style={{ fontSize: 12, color: '#a13f3f', margin: '10px 0' }}>{error}</div>}

      {showForm && (
        <form onSubmit={submit} style={{ background: 'var(--panel)', border: '1px solid var(--line)', borderRadius: 6, padding: 14, margin: '12px 0' }}>
          <div className="two-col">
            <div>
              <label>Direction</label>
              <select value={form.direction} onChange={e => set('direction', e.target.value)}>
                <option value="from_sub">From a subcontractor / supplier</option>
                <option value="to_owner">From McLoud to the owner</option>
              </select>
            </div>
            <div>
              <label>Type</label>
              <select value={form.waiver_type} onChange={e => set('waiver_type', e.target.value)}>
                {WAIVER_TYPES.map(t => <option key={t} value={t}>{WAIVER_TYPE_LABELS[t]}</option>)}
              </select>
            </div>
          </div>
          {form.direction === 'from_sub' && (
            <div className="two-col">
              <div>
                <label>Work order (fills in the sub and amount)</label>
                <select value={form.work_order_id} onChange={e => set('work_order_id', e.target.value)}>
                  <option value="">— none —</option>
                  {workOrders.filter(x => x.company_id).map(x => <option key={x.id} value={x.id}>{companies[x.company_id] || 'Sub'} — {x.trade || x.description || 'Work order'} ({fmtMoney(x.amount)})</option>)}
                </select>
              </div>
              <div>
                <label>Subcontractor</label>
                <select value={form.company_id} onChange={e => set('company_id', e.target.value)}>
                  <option value="">— choose —</option>
                  {subOptions.map(c => <option key={c} value={c}>{companies[c] || c}</option>)}
                </select>
              </div>
            </div>
          )}
          <div className="two-col">
            <div><label>Through date</label><input type="date" value={form.through_date} onChange={e => set('through_date', e.target.value)} required /></div>
            <div><label>Payment amount ($)</label><input value={form.payment_amount} onChange={e => set('payment_amount', e.target.value)} inputMode="decimal" required /></div>
          </div>
          {payApps.length > 0 && (
            <div>
              <label>Tie to a pay application (optional)</label>
              <select value={form.pay_app_id} onChange={e => set('pay_app_id', e.target.value)}>
                <option value="">— none —</option>
                {payApps.map(p => <option key={p.id} value={p.id}>Pay App #{p.application_no} — through {fmtDate(p.period_to)}</option>)}
              </select>
            </div>
          )}
          <div style={{ fontSize: 11.5, color: 'var(--ink-soft)', marginTop: 8 }}>
            The waiver text is generated from your legal company name and this job&apos;s address, and can&apos;t be edited once requested. The sub is notified right away.
          </div>
          <div className="section-actions">
            <button className="btn btn-primary btn-sm" type="submit" disabled={saving}>{saving ? 'Requesting…' : 'Request waiver'}</button>
          </div>
        </form>
      )}

      {waivers.length === 0 && !showForm && (
        <div className="empty-state">No waivers yet. Request one when you pay a subcontractor, or turn on Block mode in Settings → Automation to require them.</div>
      )}
      {subWaivers.length > 0 && (
        <>
          <h4 style={{ fontSize: 11, letterSpacing: '0.1em', textTransform: 'uppercase', color: '#9b773d', margin: '16px 0 2px' }}>From subcontractors</h4>
          {subWaivers.map(w => <Row key={w.id} w={w} />)}
        </>
      )}
      {ownerWaivers.length > 0 && (
        <>
          <h4 style={{ fontSize: 11, letterSpacing: '0.1em', textTransform: 'uppercase', color: '#9b773d', margin: '16px 0 2px' }}>To the owner</h4>
          {ownerWaivers.map(w => <Row key={w.id} w={w} />)}
        </>
      )}
    </div>
  );
}
